---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap-secret
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: CONFIG_KEY1
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: key1
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: username
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: config-volume
      configMap:
        name: sample-config
    - name: secret-volume
      secret:
        secretName: sample-secret
