name: Kind Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          version: v0.20.0
          wait: 60s

      - name: Verify cluster
        run: kubectl cluster-info

      # Apply all Secrets
      - name: Apply Secrets
        run: kubectl apply -f secrets/

      # Apply all ConfigMaps
      - name: Apply ConfigMaps
        run: kubectl apply -f configs/

      # Deploy Deployments
      - name: Apply Deployment
        run: kubectl apply -f deployment/

      # Apply Services
      - name: Apply Services
        run: kubectl apply -f services/

      # Wait for all Deployments to be ready
      - name: Wait for Pods
        run: kubectl wait --for=condition=available --timeout=60s deployment --all

      # Verify all resources
      - name: Check resources
        run: |
          echo "=== Pods ==="
          kubectl get pods -o wide
          echo "=== Secrets ==="
          kubectl get secrets
          echo "=== ConfigMaps ==="
          kubectl get configmaps
          echo "=== Services ==="
          kubectl get svc -o wide
          echo "=== Endpoints ==="
          kubectl get endpoints

      # ✅ End-to-End Service Test
      - name: Test Service connectivity
        run: |
          echo "Testing service response..."
          kubectl run curl --rm -i --restart=Never --image=curlimages/curl:latest -- \
            sh -c "curl -s sample-service:80 | grep 'Welcome to nginx'"

      # 🛠️ Debug if service test fails
      - name: Debug on failure
        if: failure()
        run: |
          echo "Service test failed ❌ - dumping debug info..."
          echo "=== Pods (with status) ==="
          kubectl get pods -o wide
          echo "=== Pod Logs (nginx) ==="
          kubectl logs -l app=nginx --tail=50 || true
          echo "=== Services ==="
          kubectl get svc -o wide
          echo "=== Endpoints ==="
          kubectl get endpoints
          echo "=== Describe Deployment (nginx) ==="
          kubectl describe deployment sample-deployment || true
          echo "=== Describe Service ==="
          kubectl describe svc sample-service || true
